/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostel.management.system;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import Project.ConnectionProvider;

/**
 *
 * @author amare
 */
public class AddStudents extends javax.swing.JFrame {
    
   

    /**
     * Creates new form AddStudents
     */
    public AddStudents() {
        initComponents();
        populateRoomNumbers();
         displayCurrentDateTime();  // Call the method to display the current date and time
        
        // Set up a timer to update the time every second
        Timer timer = new Timer(1000, new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCurrentDateTime();
            }
        });
        timer.start();  // Start the timer
    }
        public void displayCurrentDateTime() {
        // Get the current date and time
        LocalDateTime now = LocalDateTime.now();
        
        // Define a date-time format
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE, dd-MM-yyyy HH:mm:ss");

        // Format the current date-time and set it in the cdt label
        String formattedDateTime = now.format(formatter);
        cdt.setText(formattedDateTime);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        adharno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        gname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        gcno = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        relation = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emailid = new javax.swing.JTextField();
        pnumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        paddress = new javax.swing.JTextArea();
        roomnumber = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cdt = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        payment = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Student");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(341, 183));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(965, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel1.setText("Student Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 104, 100, -1));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel4.setText("Date of Birth");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 217, 82, 22));

        sname.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 101, 160, -1));

        dob.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 217, 160, -1));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 137, -1, -1));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        male.setText("Male");
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 135, -1, -1));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        female.setText("Female");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 135, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Personal Information");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 66, -1, -1));

        jLabel10.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel10.setText("Adhar No.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 264, -1, 22));

        adharno.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        adharno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adharnoKeyPressed(evt);
            }
        });
        getContentPane().add(adharno, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 264, 160, -1));

        jLabel13.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Guardian Information");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 314, -1, -1));

        jLabel14.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel14.setText("Guardian Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 358, -1, -1));

        gname.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(gname, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 355, 160, -1));

        jLabel15.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel15.setText("Guardian Contect No.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 24));

        gcno.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        gcno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcnoActionPerformed(evt);
            }
        });
        gcno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gcnoKeyPressed(evt);
            }
        });
        getContentPane().add(gcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 430, 160, -1));

        jLabel16.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel16.setText("Relation");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 395, 83, 22));

        relation.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        relation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Father", "Mother", "Brother", "Sister", "Uncle", "Aunt" }));
        getContentPane().add(relation, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 395, 160, -1));

        jLabel17.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel17.setText("Course");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 180, -1, -1));

        course.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "MCA", "MBA" }));
        getContentPane().add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 177, 160, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contect Information");

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel7.setText("Phone Number");

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel2.setText("Email Id");

        jLabel8.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel8.setText("Parmanent Address");

        emailid.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        emailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidActionPerformed(evt);
            }
        });

        pnumber.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        pnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnumberActionPerformed(evt);
            }
        });
        pnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnumberKeyPressed(evt);
            }
        });

        paddress.setColumns(20);
        paddress.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        paddress.setRows(5);
        jScrollPane1.setViewportView(paddress);

        roomnumber.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        roomnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnumberActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Room Information");

        jLabel9.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel9.setText("Allocated Room No.");

        jLabel19.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel19.setText("Check-in Time");

        cdt.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N

        clear.setBackground(new java.awt.Color(0, 0, 0));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        submit.setBackground(new java.awt.Color(0, 0, 0));
        submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        payment.setBackground(new java.awt.Color(0, 0, 0));
        payment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payment.setForeground(new java.awt.Color(255, 255, 255));
        payment.setText("Payment");
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Add New Student");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clear)
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addGap(13, 13, 13)
                .addComponent(payment)
                .addGap(8, 8, 8)
                .addComponent(back)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(55, 55, 55)
                                        .addComponent(pnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(98, 98, 98)
                                        .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(513, 513, 513)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(pnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cdt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clear)
                    .addComponent(submit)
                    .addComponent(payment)
                    .addComponent(back))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gcnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gcnoKeyPressed
        
         String guardianNumber = gcno.getText();
        int length = guardianNumber.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<10){
                gcno.setEditable(true);
            }else{
               gcno.setEditable(false);
            }
        }else{
                if(evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()== KeyEvent.VK_DELETE){
                    gcno.setEditable(true);
                }else{
                    gcno.setEditable(false);
                }
            }
    }//GEN-LAST:event_gcnoKeyPressed

    private void adharnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adharnoKeyPressed
        
        String adharNumber = adharno.getText();
        int length = adharNumber.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<12){
                adharno.setEditable(true);
            }else{
                adharno.setEditable(false);
            }
        }else{
                if(evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()== KeyEvent.VK_DELETE){
                    adharno.setEditable(true);
                }else{
                    adharno.setEditable(false);
                }
            }
    }//GEN-LAST:event_adharnoKeyPressed

        private void populateRoomNumbers() {
            
            int i=0;
         try {
             Connection con = ConnectionProvider.getCon();
         
         PreparedStatement stmt = con.prepareStatement("SELECT * FROM ROOM WHERE AVAILABILITY = 'Available'");
         ResultSet rs = stmt.executeQuery(); 
        
        while (rs.next()) {
            i=1;
            roomnumber.addItem(rs.getString("room_no"));
        }
            if(i==0){
                JOptionPane.showMessageDialog(null, "All Rooms are Already Booked");
            }
    } catch (SQLException ex) {
        Logger.getLogger(AddStudents.class.getName()).log(Level.SEVERE, null, ex);
        // Optionally, show a user-friendly error message
        JOptionPane.showMessageDialog(null, "Database error occurred while retrieving room numbers.");
    }
        }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void gcnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gcnoActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);

    }//GEN-LAST:event_backActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new StudentFees().setVisible(true);
    }//GEN-LAST:event_paymentActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        if (sname.getText().isEmpty() || emailid.getText().isEmpty() || pnumber.getText().isEmpty() || adharno.getText().trim().isEmpty() || gname.getText().isEmpty() || gcno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
            return;
        }
        String gender = "";
        if (male.isSelected()) {
            gender = "Male";
        }   else if (female.isSelected()) {
            gender = "Female";
        }

        if (dob.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select your date of birth.");
            return;
        }

        // Retrieve the selected date
        java.util.Date selectedDate = dob.getDate();

        // Validate if the selected DOB is a valid date (not a future date)
        java.util.Date currentDate = new java.util.Date(); // Get the current date

        if (selectedDate.after(currentDate)) {
            JOptionPane.showMessageDialog(this, "Date of birth cannot be in the future.");
            return;
        }

        SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy");
        String formattedDate = sf.format(selectedDate);

        String courseSelected = course.getSelectedItem().toString();
        String relationSelected = relation.getSelectedItem().toString();

        String allocatedroomSelected = roomnumber.getSelectedItem().toString();

        String paddressText = paddress.getText();
        if (paddressText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your address.");
            return;
        }
            String status = "Living";
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement stmt = con.prepareStatement("INSERT INTO ADDSTUDENT  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

            stmt.setString(1, sname.getText());
            stmt.setString(2, gender);
            stmt.setString(3,courseSelected);

            stmt.setString(4, formattedDate);

            long adharNumber = Long.parseLong(adharno.getText());
            stmt.setLong(5,adharNumber );
            long phoneNumber = Long.parseLong(pnumber.getText());
            stmt.setLong(6, phoneNumber);

            stmt.setString(7, emailid.getText());

            stmt.setString(8, paddressText);
            stmt.setString(9, allocatedroomSelected);
            stmt.setString(10, cdt.getText());

            stmt.setString(11, gname.getText());
            stmt.setString(12,relationSelected);
            long guardianNumber = Long.parseLong(gcno.getText());
            stmt.setLong(13,guardianNumber );
            stmt.setString(14, status);

            int rowsInserted = stmt.executeUpdate();
            if(rowsInserted > 0)
            {
                JOptionPane.showMessageDialog(this,  " Student Data Insert Successfully");
            }
            else{
                JOptionPane.showMessageDialog(this, " Insertion Failed");
            }

            PreparedStatement stmt1 = con.prepareStatement("UPDATE ROOM SET AVAILABILITY = 'Occupied' WHERE ROOM_NO = ? ");
            stmt1.setString(1, (String) roomnumber.getSelectedItem());
            int rowsInserted1 = stmt1.executeUpdate();

            if(rowsInserted1 > 0)
            {
                JOptionPane.showMessageDialog(this,  "Room Update Successfully");
            }
            else{
                JOptionPane.showMessageDialog(this, " Room not Occupied");
            }

        } catch (SQLException ex) {
            Logger.getLogger(AddStudents.class.getName()).log(Level.SEVERE, null, ex);
        } catch(NumberFormatException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_submitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        sname.setText("");
        emailid.setText("");
        pnumber.setText("");
        adharno.setText("");

        dob.setDate(null);

        paddress.setText("");

        gname.setText("");
        gcno.setText("");

        male.setSelected(false);
        female.setSelected(false);

        course.setSelectedIndex(0);
        relation.setSelectedIndex(0);

    }//GEN-LAST:event_clearActionPerformed

    private void roomnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnumberActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_roomnumberActionPerformed

    private void pnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnumberKeyPressed

        String phoneNumber = pnumber.getText();
        int length = phoneNumber.length();

        char c = evt.getKeyChar();

        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<10){
                pnumber.setEditable(true);
            }else{
                pnumber.setEditable(false);
            }
        }else{
            if(evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()== KeyEvent.VK_DELETE){
                pnumber.setEditable(true);
            }else{
                pnumber.setEditable(false);
            }
        }
    }//GEN-LAST:event_pnumberKeyPressed

    private void pnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnumberActionPerformed

    private void emailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adharno;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cdt;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> course;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField emailid;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField gcno;
    private javax.swing.JTextField gname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextArea paddress;
    private javax.swing.JButton payment;
    private javax.swing.JTextField pnumber;
    private javax.swing.JComboBox<String> relation;
    private javax.swing.JComboBox<String> roomnumber;
    private javax.swing.JTextField sname;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
