
package hostel.management.system;

import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author amare
 */
public class Checkout extends javax.swing.JFrame {

    /**
     * Creates new form Checkout
     */
    public Checkout() {
        initComponents();
        StudentId();
        displayCurrentDateTime();
         Timer timer = new Timer(1000, new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCurrentDateTime();
            }
        });
        timer.start();  // Start the timer
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        studentid = new javax.swing.JComboBox<>();
        checkout = new javax.swing.JButton();
        back = new javax.swing.JButton();
        roomnumber = new javax.swing.JLabel();
        checkin = new javax.swing.JLabel();
        checkouttime = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(341, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel2.setText("Student Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 128, 120, 20));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel3.setText("Room Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 166, 120, 20));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel4.setText("Checkin Time");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 207, -1, 20));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel5.setText("Checkout Time");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 247, 120, 23));

        studentid.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        studentid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studentidItemStateChanged(evt);
            }
        });
        studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidActionPerformed(evt);
            }
        });
        getContentPane().add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 125, 220, 25));

        checkout.setBackground(new java.awt.Color(0, 0, 0));
        checkout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkout.setForeground(new java.awt.Color(255, 255, 255));
        checkout.setText("Checkout");
        checkout.setPreferredSize(new java.awt.Dimension(90, 31));
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });
        getContentPane().add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 297, 94, 30));

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Back.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 297, 94, -1));

        roomnumber.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(roomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 166, 220, 25));

        checkin.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        checkin.setPreferredSize(new java.awt.Dimension(72, 23));
        getContentPane().add(checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 207, 220, 25));

        checkouttime.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        checkouttime.setPreferredSize(new java.awt.Dimension(72, 23));
        getContentPane().add(checkouttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 247, 220, 25));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Checkout");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(453, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 968, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        // TODO add your handling code here:
            try{
            Connection con = ConnectionProvider.getCon();
            PreparedStatement stmt = con.prepareStatement("UPDATE ADDSTUDENT SET STATUS = 'Leaved' WHERE ADHAR_NO = '"+studentid.getSelectedItem()+"'");
            stmt.executeUpdate(); 
            
            PreparedStatement stmt2 = con.prepareStatement("UPDATE ROOM SET AVAILABILITY = 'Available' WHERE ROOM_NO = '"+roomnumber.getText()+"'");
            stmt2.executeUpdate(); 
            
           JOptionPane.showMessageDialog(this, "Checkout Done");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Database error.");
                }
    }//GEN-LAST:event_checkoutActionPerformed

    private void studentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_studentidActionPerformed

    private void studentidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentidItemStateChanged
       
        try {
        
        String selectedStudentId = studentid.getSelectedItem().toString();
      
        Connection con = ConnectionProvider.getCon();
        
     
        PreparedStatement stmt = con.prepareStatement("SELECT * FROM ADDSTUDENT WHERE ADHAR_NO = ?");
        stmt.setString(1, selectedStudentId);  
        
        ResultSet rs = stmt.executeQuery(); 
        
        
        if (rs.next()) {
            roomnumber.setText(rs.getString("ALLOCATED_ROOM"));
            checkin.setText(rs.getString("CHECK_IN_TIME"));
        }
        
    } catch(SQLException e) {
        
        System.err.println("Error fetching student details: " + e.getMessage());
        JOptionPane.showMessageDialog(this, "Database error.");
    }
    }//GEN-LAST:event_studentidItemStateChanged

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_backActionPerformed

    public void displayCurrentDateTime() {
    Date date = new Date(); 
    SimpleDateFormat formatter = new SimpleDateFormat("EEEE, dd-MM-yyyy HH:mm:ss");
    String formattedDate = formatter.format(date); 
    checkouttime.setText(formattedDate);
    }

     private void StudentId() {
    try {
        // Establish the database connection
        Connection con = ConnectionProvider.getCon();
        
        // Prepare the SQL query to fetch ADHAR_NO where status is 'Living'
        PreparedStatement stmt = con.prepareStatement("SELECT * FROM ADDSTUDENT WHERE status = 'Living'");
        
        // Execute the query
        ResultSet rs = stmt.executeQuery();
        
        // Iterate through the result set and add ADHAR_NO to the combo box
        while (rs.next()) {
            studentid.addItem(rs.getString("ADHAR_NO"));
        }
        
    } catch (SQLException e) {
        // Handle SQL exception
        System.err.println("Error fetching student IDs: " + e.getMessage());
        JOptionPane.showMessageDialog(this, "Database error.");
    }
}

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel checkin;
    private javax.swing.JButton checkout;
    private javax.swing.JLabel checkouttime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel roomnumber;
    private javax.swing.JComboBox<String> studentid;
    // End of variables declaration//GEN-END:variables
}
