/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostel.management.system;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author amare
 */
public class DS extends javax.swing.JFrame {

    /**
     * Creates new form DS
     */

    Color DefaultColor,ClickedColor;
    public DS() {
        initComponents();
        DefaultColor = new Color(0,51,51);
        ClickedColor = new Color(255,102,0);
        
        newstu.setBackground(DefaultColor);
        newroom.setBackground(DefaultColor);
        stuinfo.setBackground(DefaultColor);
        searchroom.setBackground(DefaultColor);
        feepay.setBackground(DefaultColor);
        paystatus.setBackground(DefaultColor);
        checkout.setBackground(DefaultColor);
        leavedstu.setBackground(DefaultColor);
        about.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cancel = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        newstu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        newroom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stuinfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchroom = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        feepay = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        paystatus = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        checkout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        leavedstu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 650));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(1250, 155));
        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Close.png"))); // NOI18N
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelMousePressed(evt);
            }
        });
        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 50, 40));

        logout.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 120, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Iconshock-Super-Vista-General-Home.128.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 190, 130));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("HostelMate");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 300, 50));

        about.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setText("About HostelMate");
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutMousePressed(evt);
            }
        });
        jPanel2.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 100, 130, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(220, 550));

        newstu.setBackground(new java.awt.Color(0, 51, 51));
        newstu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newstuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newstuMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("New Student");

        javax.swing.GroupLayout newstuLayout = new javax.swing.GroupLayout(newstu);
        newstu.setLayout(newstuLayout);
        newstuLayout.setHorizontalGroup(
            newstuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newstuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newstuLayout.setVerticalGroup(
            newstuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        newroom.setBackground(new java.awt.Color(0, 51, 51));
        newroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newroomMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newroomMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Room");

        javax.swing.GroupLayout newroomLayout = new javax.swing.GroupLayout(newroom);
        newroom.setLayout(newroomLayout);
        newroomLayout.setHorizontalGroup(
            newroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newroomLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newroomLayout.setVerticalGroup(
            newroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        stuinfo.setBackground(new java.awt.Color(0, 51, 51));
        stuinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stuinfoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stuinfoMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student Information's");

        javax.swing.GroupLayout stuinfoLayout = new javax.swing.GroupLayout(stuinfo);
        stuinfo.setLayout(stuinfoLayout);
        stuinfoLayout.setHorizontalGroup(
            stuinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stuinfoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stuinfoLayout.setVerticalGroup(
            stuinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        searchroom.setBackground(new java.awt.Color(0, 51, 51));
        searchroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchroomMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchroomMousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Search Rooms");

        javax.swing.GroupLayout searchroomLayout = new javax.swing.GroupLayout(searchroom);
        searchroom.setLayout(searchroomLayout);
        searchroomLayout.setHorizontalGroup(
            searchroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchroomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        searchroomLayout.setVerticalGroup(
            searchroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        feepay.setBackground(new java.awt.Color(0, 51, 51));
        feepay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feepayMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                feepayMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fee Payment");

        javax.swing.GroupLayout feepayLayout = new javax.swing.GroupLayout(feepay);
        feepay.setLayout(feepayLayout);
        feepayLayout.setHorizontalGroup(
            feepayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feepayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        feepayLayout.setVerticalGroup(
            feepayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        paystatus.setBackground(new java.awt.Color(0, 51, 51));
        paystatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paystatusMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paystatusMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 51, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Payment Status");

        javax.swing.GroupLayout paystatusLayout = new javax.swing.GroupLayout(paystatus);
        paystatus.setLayout(paystatusLayout);
        paystatusLayout.setHorizontalGroup(
            paystatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paystatusLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        paystatusLayout.setVerticalGroup(
            paystatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        checkout.setBackground(new java.awt.Color(0, 51, 51));
        checkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkoutMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 51, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Checkout");

        javax.swing.GroupLayout checkoutLayout = new javax.swing.GroupLayout(checkout);
        checkout.setLayout(checkoutLayout);
        checkoutLayout.setHorizontalGroup(
            checkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        checkoutLayout.setVerticalGroup(
            checkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        leavedstu.setBackground(new java.awt.Color(0, 51, 51));
        leavedstu.setPreferredSize(new java.awt.Dimension(245, 50));
        leavedstu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leavedstuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                leavedstuMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Leaved Students");

        javax.swing.GroupLayout leavedstuLayout = new javax.swing.GroupLayout(leavedstu);
        leavedstu.setLayout(leavedstuLayout);
        leavedstuLayout.setHorizontalGroup(
            leavedstuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leavedstuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        leavedstuLayout.setVerticalGroup(
            leavedstuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(newstu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stuinfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(feepay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paystatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leavedstu, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(newstu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(newroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(stuinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(searchroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(feepay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(paystatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(leavedstu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(900, 0));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newstuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newstuMousePressed
        // TODO add your handling code here:
        newstu.setBackground(ClickedColor);
        newroom.setBackground(DefaultColor);
        stuinfo.setBackground(DefaultColor);
        searchroom.setBackground(DefaultColor);
        feepay.setBackground(DefaultColor);
        paystatus.setBackground(DefaultColor);
        checkout.setBackground(DefaultColor);
        leavedstu.setBackground(DefaultColor);
        about.setBackground(DefaultColor);
    }//GEN-LAST:event_newstuMousePressed

    private void newroomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newroomMousePressed
        // TODO add your handling code here:
        newstu.setBackground(DefaultColor);
        newroom.setBackground(ClickedColor);
        stuinfo.setBackground(DefaultColor);
        searchroom.setBackground(DefaultColor);
        feepay.setBackground(DefaultColor);
        paystatus.setBackground(DefaultColor);
        checkout.setBackground(DefaultColor);
        leavedstu.setBackground(DefaultColor);
        about.setBackground(DefaultColor);
    }//GEN-LAST:event_newroomMousePressed

    private void stuinfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuinfoMousePressed
        // TODO add your handling code here:
        newstu.setBackground(DefaultColor);
        newroom.setBackground(DefaultColor);
        stuinfo.setBackground(ClickedColor);
        searchroom.setBackground(DefaultColor);
        feepay.setBackground(DefaultColor);
        paystatus.setBackground(DefaultColor);
        checkout.setBackground(DefaultColor);
        leavedstu.setBackground(DefaultColor);
        about.setBackground(DefaultColor);
    }//GEN-LAST:event_stuinfoMousePressed

    private void searchroomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchroomMousePressed
        // TODO add your handling code here:
        newstu.setBackground(DefaultColor);
        newroom.setBackground(DefaultColor);
        stuinfo.setBackground(DefaultColor);
        searchroom.setBackground(ClickedColor);
        feepay.setBackground(DefaultColor);
        paystatus.setBackground(DefaultColor);
        checkout.setBackground(DefaultColor);
        leavedstu.setBackground(DefaultColor);
        about.setBackground(DefaultColor);
    }//GEN-LAST:event_searchroomMousePressed

    private void feepayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feepayMousePressed
        // TODO add your handling code here:
        newstu.setBackground(DefaultColor);
        newroom.setBackground(DefaultColor);
        stuinfo.setBackground(DefaultColor);
        searchroom.setBackground(DefaultColor);
        feepay.setBackground(ClickedColor);
        paystatus.setBackground(DefaultColor);
        checkout.setBackground(DefaultColor);
        leavedstu.setBackground(DefaultColor);
        about.setBackground(DefaultColor);
    }//GEN-LAST:event_feepayMousePressed

    private void paystatusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paystatusMousePressed
        // TODO add your handling code here:
        newstu.setBackground(DefaultColor);
        newroom.setBackground(DefaultColor);
        stuinfo.setBackground(DefaultColor);
        searchroom.setBackground(DefaultColor);
        feepay.setBackground(DefaultColor);
        paystatus.setBackground(ClickedColor);
        checkout.setBackground(DefaultColor);
        leavedstu.setBackground(DefaultColor);
        about.setBackground(DefaultColor);
    }//GEN-LAST:event_paystatusMousePressed

    private void checkoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutMousePressed
        // TODO add your handling code here:
        newstu.setBackground(DefaultColor);
        newroom.setBackground(DefaultColor);
        stuinfo.setBackground(DefaultColor);
        searchroom.setBackground(DefaultColor);
        feepay.setBackground(DefaultColor);
        paystatus.setBackground(DefaultColor);
        checkout.setBackground(ClickedColor);
        leavedstu.setBackground(DefaultColor);
        about.setBackground(DefaultColor);
    }//GEN-LAST:event_checkoutMousePressed

    private void cancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMousePressed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Close Application","Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
        System.exit(0);
     }
    }//GEN-LAST:event_cancelMousePressed

    private JFrame currentFrame = null;
    private void newstuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newstuMouseClicked
        // TODO add your handling code here:
        if (currentFrame != null) {
        currentFrame.dispose();  // Dispose of the previous form
    }
     AddStudents stu = new AddStudents();
     stu.setVisible(true);
     currentFrame = stu;
    }//GEN-LAST:event_newstuMouseClicked

    private void newroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newroomMouseClicked
        // TODO add your handling code here:
        if (currentFrame != null) {
        currentFrame.dispose();  // Dispose of the previous form
    }
     AddRooms rom = new AddRooms();
     rom.setVisible(true);
        currentFrame = rom;
    }//GEN-LAST:event_newroomMouseClicked

    private void stuinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuinfoMouseClicked
        // TODO add your handling code here:
        if (currentFrame != null) {
        currentFrame.dispose();  // Dispose of the previous form
    }
        StudentsInfo studinfo = new StudentsInfo();
        studinfo.setVisible(true);
        currentFrame = studinfo;
    }//GEN-LAST:event_stuinfoMouseClicked

    private void searchroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchroomMouseClicked
        // TODO add your handling code here:
        if (currentFrame != null) {
        currentFrame.dispose();  // Dispose of the previous form
    }
        SearchRooms sr = new SearchRooms();
        sr.setVisible(true);
        currentFrame = sr;
    }//GEN-LAST:event_searchroomMouseClicked

    private void feepayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feepayMouseClicked
        // TODO add your handling code here:
        if (currentFrame != null) {
        currentFrame.dispose();  // Dispose of the previous form
    }
        StudentFees fee = new StudentFees();
        fee.setVisible(true);
        currentFrame = fee;
    }//GEN-LAST:event_feepayMouseClicked

    private void paystatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paystatusMouseClicked
        // TODO add your handling code here:
         if (currentFrame != null) {
        currentFrame.dispose();  // Dispose of the previous form
    }
        PaymentStatus pay = new PaymentStatus();
        pay.setVisible(true);
        currentFrame = pay;
    }//GEN-LAST:event_paystatusMouseClicked

    private void checkoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutMouseClicked
        // TODO add your handling code here:
        if (currentFrame != null) {
        currentFrame.dispose();  // Dispose of the previous form
    }
        Checkout chk = new Checkout();
        chk.setVisible(true);
        currentFrame = chk;
    }//GEN-LAST:event_checkoutMouseClicked

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Logout","Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
        setVisible(false);
        new Login().setVisible(true);
     }
    }//GEN-LAST:event_logoutMousePressed

    private void leavedstuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavedstuMousePressed
        // TODO add your handling code here:
        newstu.setBackground(DefaultColor);
        newroom.setBackground(DefaultColor);
        stuinfo.setBackground(DefaultColor);
        searchroom.setBackground(DefaultColor);
        feepay.setBackground(DefaultColor);
        paystatus.setBackground(DefaultColor);
        checkout.setBackground(DefaultColor);
        leavedstu.setBackground(ClickedColor);
        about.setBackground(DefaultColor);
    }//GEN-LAST:event_leavedstuMousePressed

    private void leavedstuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavedstuMouseClicked
        // TODO add your handling code here:
        if (currentFrame != null) {
        currentFrame.dispose();  // Dispose of the previous form
    }
        LeavedStudents ls = new LeavedStudents();
        ls.setVisible(true);
        currentFrame = ls;
    }//GEN-LAST:event_leavedstuMouseClicked

    private void aboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMousePressed
        // TODO add your handling code here:
        newstu.setBackground(DefaultColor);
        newroom.setBackground(DefaultColor);
        stuinfo.setBackground(DefaultColor);
        searchroom.setBackground(DefaultColor);
        feepay.setBackground(DefaultColor);
        paystatus.setBackground(DefaultColor);
        checkout.setBackground(DefaultColor);
        leavedstu.setBackground(DefaultColor);
        about.setBackground(ClickedColor);
    }//GEN-LAST:event_aboutMousePressed

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
         if (currentFrame != null) {
        currentFrame.dispose();  // Dispose of the previous form
    }
        AboutUs as = new AboutUs();
        as.setVisible(true);
        currentFrame = as;
    }//GEN-LAST:event_aboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel cancel;
    private javax.swing.JPanel checkout;
    private javax.swing.JPanel feepay;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel leavedstu;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel newroom;
    private javax.swing.JPanel newstu;
    private javax.swing.JPanel paystatus;
    private javax.swing.JPanel searchroom;
    private javax.swing.JPanel stuinfo;
    // End of variables declaration//GEN-END:variables
}
