/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostel.management.system;

import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author amare
 */
public class PaymentStatus extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCheck
     */
    public PaymentStatus() {
        initComponents();
        StudentId();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pending = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pay = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        livedin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        payingamount = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paytable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        check = new javax.swing.JButton();
        back = new javax.swing.JButton();
        sname = new javax.swing.JLabel();
        studentid = new javax.swing.JComboBox<>();
        room = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(341, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel2.setText("Student Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 96, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel3.setText("Student Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 138, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel4.setText("Room No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 176, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel6.setText("Room Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 218, 98, -1));

        price.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 180, 24));

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel7.setText("Pending Amount");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 380, 110, -1));

        pending.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(pending, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 372, 178, 24));

        jLabel8.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel8.setText("Student Pay");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 338, -1, -1));

        pay.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 180, 24));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel5.setText("Lived-In");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 254, 98, -1));

        livedin.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(livedin, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 246, 178, 24));

        jLabel9.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel9.setText("Paying Amount");
        jLabel9.setPreferredSize(new java.awt.Dimension(43, 16));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 296, 98, -1));

        payingamount.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(payingamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 288, 180, 24));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(968, 500));

        paytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(paytable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payment Status");

        check.setBackground(new java.awt.Color(0, 0, 0));
        check.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        check.setText("Check");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Back.png"))); // NOI18N
        back.setText("Back");
        back.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        sname.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N

        studentid.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidActionPerformed(evt);
            }
        });

        room.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(check)
                        .addGap(18, 18, 18)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(studentid, 0, 178, Short.MAX_VALUE)
                            .addComponent(sname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(room, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(117, 117, 117)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 968, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_studentidActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
        String id = (String) studentid.getSelectedItem();
    
        
        LocalDate checkInDate = null;
        int roomPrice = 0;
        float payingAmount = 0;
        int paidAmount = 0;
        
        try{
            Connection con = ConnectionProvider.getCon();
            PreparedStatement stmt = con.prepareStatement("SELECT CHECK_IN_TIME FROM ADDSTUDENT WHERE ADHAR_NO = ?");
            stmt.setString(1, id); 
            ResultSet rs = stmt.executeQuery(); 
          

    // Process the result
        if (rs.next()) {
        String checkInStr = rs.getString("CHECK_IN_TIME");
        if (checkInStr != null) {
            // Define the DateTimeFormatter to match the provided format ("EEEE, dd-MM-yyyy HH:mm:ss")
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE, dd-MM-yyyy HH:mm:ss");

            // Parse the date string to a LocalDate (ignore the time part)
            LocalDateTime checkInDateTime = LocalDateTime.parse(checkInStr, formatter);
            checkInDate = checkInDateTime.toLocalDate();  // Extract only the date part (dd-MM-yyyy)
            con.close();
        } else {
            JOptionPane.showMessageDialog(this,"Check-in date is null");
            checkInDate = null;
        }
    }

    // Calculate days lived
    if (checkInDate != null) {
        LocalDate currentDate = LocalDate.now();
        long daysLived = ChronoUnit.DAYS.between(checkInDate, currentDate);
        livedin.setText(String.valueOf(daysLived)); // Update JLabel with number of days
    } else {
        livedin.setText("No check-in date available");
    }
    
}       catch (SQLException ex) {
            Logger.getLogger(PaymentStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
    // Establishing connection to the database
    Connection con = ConnectionProvider.getCon();
    
    // Query to fetch all payments made by the student
    PreparedStatement stmt = con.prepareStatement("SELECT * FROM STUDENTPAYMENT WHERE STUDENT_ID = ?");
    stmt.setString(1, id); 
    
    // Execute the query and get the result set
    ResultSet rs = stmt.executeQuery();
    
    // Prepare to display payment records in the table
    DefaultTableModel tbl = (DefaultTableModel) paytable.getModel();
    String[] colName = {"MONTH", "STUDENT PAY", "PAYMENT DATE"};
    tbl.setRowCount(0);  // Clear previous rows in the table
    tbl.setColumnIdentifiers(colName);  // Set the column names for the table
    
    // Variable to accumulate the total amount paid by the student
    double totalPaid = 0.0;

    // Loop through each payment record
    while (rs.next()) {
        // Fetch the relevant details for each payment
        String month = rs.getString("MONTH");
        String studentPay = String.valueOf(rs.getLong("STUDENT_PAY"));
        String paymentDate = rs.getString("PAYMENT_DATE");
        
        // Add the student payment to the totalPaid amount
        totalPaid += Double.parseDouble(studentPay);
        
        // Add a new row to the table with the month, student payment, and payment date
        String[] tdata = {month, studentPay, paymentDate};
        tbl.addRow(tdata);
        
        // Set additional student details for the UI (e.g., name, room, price)
        sname.setText(rs.getString("NAME"));
        room.setText(rs.getString("ROOM_NO"));
        price.setText(rs.getString("ROOM_PRICE"));  
        
        // Parse the room price for calculations
        roomPrice = (int) Double.parseDouble(rs.getString("ROOM_PRICE"));
    }
    
    // Calculate the paying amount and pending amount only if check-in date is available
    if (checkInDate != null) {
        long daysLived = Long.parseLong(livedin.getText());  // Get the number of days lived
        YearMonth checkInYearMonth = YearMonth.from(checkInDate); // Get YearMonth from check-in date
        int daysInMonth = checkInYearMonth.lengthOfMonth(); // Get the actual number of days in the month
        
        // Calculate the daily rate
        float dailyRate = (float) (roomPrice / daysInMonth);
        // Calculate the paying amount based on the days lived
        payingAmount = dailyRate * daysLived;

        // Display the calculated paying amount
        payingamount.setText(String.valueOf(payingAmount));
        
        // Display the total paid amount
        pay.setText(String.valueOf(totalPaid));

        // Calculate the pending amount
        float pendingAmount = (float) (payingAmount - totalPaid);
        pending.setText(String.valueOf(pendingAmount));
    }
        con.close();
}       catch (SQLException e) {
// Handle any SQL exceptions
        JOptionPane.showMessageDialog(null, "An error occurred while fetching data: " + e.getMessage());
}

    }//GEN-LAST:event_checkActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_backActionPerformed
    private void StudentId(){
        try {
        
        Connection con = ConnectionProvider.getCon();
        
        PreparedStatement stmt = con.prepareStatement("SELECT * FROM ADDSTUDENT WHERE status = 'Living'");
        
        ResultSet rs = stmt.executeQuery();
        
        while (rs.next()) {
            studentid.addItem(rs.getString("ADHAR_NO"));
        }
        
    } catch (SQLException e) {
        
        System.err.println("Error fetching student IDs: " + e.getMessage());
        JOptionPane.showMessageDialog(this, "Database error.");
    }
    }
     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel livedin;
    private javax.swing.JLabel pay;
    private javax.swing.JLabel payingamount;
    private javax.swing.JTable paytable;
    private javax.swing.JLabel pending;
    private javax.swing.JLabel price;
    private javax.swing.JLabel room;
    private javax.swing.JLabel sname;
    private javax.swing.JComboBox<String> studentid;
    // End of variables declaration//GEN-END:variables
}
