/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostel.management.system;

import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author amare
 */
public class StudentFees extends javax.swing.JFrame {

    /**
     * Creates new form UpdateRoomStatus
     */
    public StudentFees() {
        initComponents();
        StudentId();
          displayCurrentDateTime();
         Timer timer = new Timer(1000, new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCurrentDateTime();
            }
        });
        timer.start();  // Start the timer
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        studentid = new javax.swing.JComboBox<>();
        roomnumber = new javax.swing.JTextField();
        roomprice = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        save = new javax.swing.JButton();
        back = new javax.swing.JButton();
        pay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        paydate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(340, 184));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 38));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel2.setText("Student Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 131, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel3.setText("Room Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 214, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel4.setText("Month");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 254, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel5.setText("Room Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 294, -1, -1));

        studentid.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 128, 200, -1));

        roomnumber.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(roomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 211, 300, -1));

        roomprice.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(roomprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 291, 300, -1));

        search.setBackground(new java.awt.Color(51, 51, 51));
        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 126, 100, -1));

        save.setBackground(new java.awt.Color(51, 51, 51));
        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 371, 100, 30));

        back.setBackground(new java.awt.Color(51, 51, 51));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Back.png"))); // NOI18N
        back.setText("Back");
        back.setActionCommand("");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 373, 90, -1));

        pay.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 331, 300, -1));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel6.setText("Student Pay");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 334, -1, -1));

        month.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 251, 300, -1));

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel7.setText("Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 174, -1, -1));

        name.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 171, 300, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        paydate.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(722, Short.MAX_VALUE)
                .addComponent(paydate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(paydate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 968, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String id = (String) studentid.getSelectedItem();
        String sname = name.getText();
        String room = roomnumber.getText();
        String Month = month.getText();
        String price = roomprice.getText();
        String spay = pay.getText();
        String date = paydate.getText();
        
        
      
      
       try{
            Connection con = ConnectionProvider.getCon();
            PreparedStatement stmt = con.prepareStatement("INSERT INTO STUDENTPAYMENT VALUES (?, ?, ?, ?, ?, ?, ?)");
            stmt.setString(1, id);
            
            stmt.setString(2, sname);
            
            stmt.setString(3, room);
            
            stmt.setString(4,price);
            
            stmt.setString(5, Month);
            
            stmt.setString(6, spay);
            
            stmt.setString(7, date);
            

            int rowsInserted = stmt.executeUpdate();
            if(rowsInserted > 0)
            {
                JOptionPane.showMessageDialog(this,  " Payment Successfull");
            }
            else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
         
    }//GEN-LAST:event_saveActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
        String id = (String) studentid.getSelectedItem();
        Date date = new Date(); 
        SimpleDateFormat dformat = new SimpleDateFormat("MMMM-yyyy");
        String Month = dformat.format(date);
       
        try{
            Connection con = ConnectionProvider.getCon();
            PreparedStatement stmt = con.prepareStatement("SELECT * FROM ADDSTUDENT WHERE ADHAR_NO = '"+id+"'");
            ResultSet rs = stmt.executeQuery(); 
            
            while(rs.next()) {
            name.setText(rs.getString("STUDENT_NAME"));
            roomnumber.setText(rs.getString("ALLOCATED_ROOM"));
            month.setText(Month);
          }
             PreparedStatement stmt2 = con.prepareStatement("SELECT * FROM ROOM WHERE ROOM_NO = '"+roomnumber.getText()+"'");
             ResultSet rs2 = stmt2.executeQuery(); 
            
            while(rs2.next()) {
               
                roomprice.setText(rs2.getString("PRICE"));
            }
        }catch(SQLException e){
                }
    }//GEN-LAST:event_searchActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_backActionPerformed
        private void StudentId(){
      try {
        // Establish the database connection
        Connection con = ConnectionProvider.getCon();
        
        // Prepare the SQL query to fetch ADHAR_NO where status is 'Living'
        PreparedStatement stmt = con.prepareStatement("SELECT * FROM ADDSTUDENT WHERE status = 'Living'");
        
        // Execute the query
        ResultSet rs = stmt.executeQuery();
        
        // Iterate through the result set and add ADHAR_NO to the combo box
        while (rs.next()) {
            studentid.addItem(rs.getString("ADHAR_NO"));
        }
        
    } catch (SQLException e) {
        // Handle SQL exception
        System.err.println("Error fetching student IDs: " + e.getMessage());
        JOptionPane.showMessageDialog(this, "Database error.");
    }
}
        public void displayCurrentDateTime() {
        Date date = new Date(); 
        SimpleDateFormat formatter = new SimpleDateFormat("EEEE dd-MM-yyyy HH:mm:ss");
        String formattedDate = formatter.format(date); 
        paydate.setText(formattedDate);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField month;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pay;
    private javax.swing.JLabel paydate;
    private javax.swing.JTextField roomnumber;
    private javax.swing.JTextField roomprice;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> studentid;
    // End of variables declaration//GEN-END:variables
}
